apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.deploymentname }}
  namespace: "{{ .Values.deployment.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.deploymentname }}
      namespace: "{{ .Values.deployment.namespace }}"
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.deploymentname }}
        namespace: "{{ .Values.deployment.namespace }}"
    spec:
      containers:
      - name: werewolf-deployment
        image: {{ .Values.image.repository }}/werewolf:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: werewolfport8080