{{- if .Values.juiceShopCleanup.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juice-cleaner
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
{{- end }}
