kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: juice-balancer-ingress
  namespace: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true" 
    nginx.org/mergeable-ingress-type: "minion"   
spec:
  rules:
    - http:
        paths:
          - path: /juicectf/?(.*)
            backend:
              serviceName: juice-balancer
              servicePort: 3000
      host: "diesenreiter.com"