kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: website-ingress
  namespace: "{{ .Values.deployment.namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"    
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: {{ .Values.deployment.servicename }}
              servicePort: 80
      host: "diesenreiter.com"