apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.servicename }}
  namespace: "{{ .Values.deployment.namespace }}"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: "http" 
      targetPort: 80
  selector:
    app: {{ .Values.deployment.deploymentname }}
    namespace: "{{ .Values.deployment.namespace }}"